import { NgModule } from '@angular/core';
/**
 * Modulos angular material
 */
import {
  MatButtonModule,
  MatCheckboxModule,
  MatButtonToggleModule,
  MatToolbarModule,
  MatIconModule,
  MatTableModule,
  MatSidenavModule,
  MatRadioModule,
  MatListModule,
  MatCardModule,
  MatFormFieldModule,
  MatSelectModule,
  MatInputModule,
  MatMenuModule,
  MatSnackBarModule,
  MatPaginatorModule,
  MatTabsModule,
  MatSortModule,
  MatBadgeModule,
  MatProgressSpinnerModule,
  MatTooltipModule,
  MatBottomSheetModule,
  MatExpansionModule,
} from '@angular/material';

@NgModule({
  imports: [
    MatButtonModule,
    MatCheckboxModule,
    MatButtonToggleModule,
    MatToolbarModule,
    MatIconModule,
    MatTableModule,
    MatSidenavModule,
    MatRadioModule,
    MatListModule,
    MatCardModule,
    MatFormFieldModule,
    MatSelectModule,
    MatInputModule,
    MatMenuModule,
    MatSnackBarModule,
    MatPaginatorModule,
    MatTabsModule,
    MatSortModule,
    MatBadgeModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatBottomSheetModule,
    MatExpansionModule
  ],
  exports: [
    MatButtonModule,
    MatCheckboxModule,
    MatButtonToggleModule,
    MatToolbarModule,
    MatIconModule,
    MatTableModule,
    MatSidenavModule,
    MatRadioModule,
    MatListModule,
    MatCardModule,
    MatFormFieldModule,
    MatSelectModule,
    MatInputModule,
    MatMenuModule,
    MatSnackBarModule,
    MatPaginatorModule,
    MatTabsModule,
    MatSortModule,
    MatBadgeModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatBottomSheetModule,
    MatExpansionModule
  ],
  declarations: []
})
export class MaterialModule { }
